### ISSUE TITLE
404 page gets broken by insertion of <base href="/">

### ISSUE THREAD

**Issue by morgenman** [mdzk-rs/mdzk#57]
I noticed that mdzk breaks [404 pages](https://kmaasrud.com/brain/doesNotExist) (css doesn't load), even when manually created through a 404.md file. 
I made an identical md file and called it something else, and it worked!
After looking at the code, it seems that a line is added for 404 files:
```html
    <base href="/">
```
Not sure why this is being added, but removing it allows them to be restyled again. 
Not sure if this is a big issue, but thought it might be helpful!

**Comment by kmaasrud** [comment]
> ```html
>     <base href="/">
> ```

Where is this found? Is it part of mdBook? I don' t think we do anything special with 404-files...

**Comment by morgenman** [comment]
This is found in html files generated by mdzk. That is to say, lines 8-10 of index.hbs cause it to be included:
```html
    {{#if base_url}}
        <base href="{{ base_url }}">
    {{/if}}
```
It doesn't affect any other pages negatively, I'm not sure why. 
I would have assumed it was due to me hosting on gh-pages, except for the fact that your 'brain' has it too. The link on my first message links to your site. 
When I switched to a custom domain (where everything is hosted on root), it ended up working with it included. I think the actual issue is the url supplied by the `{{ base_url }}` placeholder. When it's a valid page, context is retained, but when it's not, it defaults to the root of the site. 
I don't know if that makes sense.

**Comment by kmaasrud** [comment]
Oh, of course, I just found where I've seen this before!

https://github.com/rust-lang/mdBook/blob/17d1ed3716932222dd05f0cc9cde38d31543de2b/src/renderer/html_handlebars/hbs_renderer.rs#L159-L168

If you host your mdzk in a sub-directory, then you need to specify the `output.html.site-url` configuration value so the correct URLs are produced to the asset files. In my case, since I host on `/brain`, I should configure my vault thusly:

```toml
[output.html]
site-url = "/brain"
```

In your case, since your notes are on the base of your domain, the [404](https://notes.morgenman.me/notexist) works correctly. I will close this issue, but feel free to reopen it if you find any edge cases or you think there is something here we should improve upon :smile:
